### ISSUE TITLE
idrnnclus's min_weight_full_bipartite_matching throws uncaught ValueError

### ISSUE THREAD

**Issue by cstenkamp** [frankier/skelshop#53]
Hi Frankie,

When I want to run `skelshop iden idrnnclus .../ref.h5 .../model.rnndbscan.pkl .../rnndbscan.cluster.labels.csv`, with the given files, SciPy's `min_weight_full_bipartite_matching` (@ https://github.com/frankier/skelshop/blob/master/skelshop/cmd/iden/idrnnclus.py#L54) throws me a ValueError " no full matching exists", which is uncaught and lets the skelshop fail.
Can that simply be wrapped inside a try-catch-block, or is there any other way to resolve that?

[rnndbscan_fail.zip](https://github.com/frankier/skelshop/files/6150475/rnndbscan_fail.zip)

**Comment by frankier** [comment]
Whoops! Looks like I didn't test that with more than one reference! It seems to be fixed now so you can get the new version which has also just been rebuilt https://gitlab.com/frankier/skelshop/-/commit/a3f38ddbf450627f5f9b30d296753ebbc04cd920/pipelines?ref=master

**Comment by frankier** [comment]
BTW thanks for making it easy to replicate. Let me know if it fixed your problem so I can close this issue.

**Comment by cstenkamp** [comment]
Hey, thanks a lot for being so quick on this! 
So far however it seems like the container hasn't been rebuilt (https://hub.docker.com/r/frankierr/skelshop/builds)? 
Can you trigger the build manually? I don't think I can for your dockerhub account

**Comment by frankier** [comment]
It's building and I've invited you to the Docker Hub. Probably I should migrate to GitHub Actions since Docker Hub is so throttled now but I will ping you when it's built.

**Comment by frankier** [comment]
Although actually now I come to mention it, you don't necessarily need a totally new container in this case. I wrote a bit about speeding things up using this here: https://frankie.robertson.name/research/effective-cluster-computing/#use-binds

**Comment by frankier** [comment]
Okay looks like it's done now.

**Comment by cstenkamp** [comment]
oh wow, that took quite some time! Thanks though!

**Comment by frankier** [comment]
Yeah it's to do with Docker Hub's new throttling I think. Builds get stuck in the queue forever.

**Comment by cstenkamp** [comment]
seems to work, thanks a lot! :)
